# Generated by Django 5.1.6 on 2025-02-13 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_date', models.DateTimeField(verbose_name='date published')),
                ('model', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=200)),
                ('sessionid', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Communication_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gen_date', models.DateTimeField(verbose_name='date published')),
                ('role', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=4000)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.communication')),
            ],
        ),
        migrations.AddField(
            model_name='communication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.user'),
        ),
    ]
