# Generated by Django 5.1.6 on 2025-02-16 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sessionid_expire',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 16, 5, 53, 8, 869172, tzinfo=datetime.timezone.utc), verbose_name='sessionid expire'),
            preserve_default=False,
        ),
    ]
