# Generated by Django 5.1.6 on 2025-02-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_user_sessionid_expire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='votes',
        ),
        migrations.AlterField(
            model_name='user',
            name='sessionid',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.IntegerField(default=-1),
        ),
    ]
