"""
Django settings for llmsite project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os

DEBUG = False
TALK_TEST = False

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Application definition

INSTALLED_APPS = [
	'django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	"mainsite.apps.MainsiteConfig",
]

MIDDLEWARE = [
	'django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'llmsite.middleware.UserAuthMiddleware',
]

ROOT_URLCONF = 'llmsite.urls'

TEMPLATES = [
	{
		'BACKEND': 'django.template.backends.django.DjangoTemplates',
		'DIRS': [BASE_DIR / 'llmsite/templates'],
		'APP_DIRS': True,
		'OPTIONS': {
			'context_processors': [
				'django.template.context_processors.debug',
				'django.template.context_processors.request',
				'django.contrib.auth.context_processors.auth',
				'django.contrib.messages.context_processors.messages',
			],
		},
	},
]

WSGI_APPLICATION = 'llmsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASE_ENGINE = 'django.db.backends.sqlite3'
DATABASE_NAME = BASE_DIR / 'db.sqlite3'
DATABASE_USER = ""
DATABASE_PASSWORD = ""
DATABASE_HOST = "127.0.0.1"
DATABASE_PORT = ""
DATABASE_OPTIONS = {}
SECRET_KEY = 'django-insecure-#w@25vu=80@@y&(arepi@=j$ad!f#iy2q9^ga#t5%5*c12d^o&'
ALLOWED_HOSTS = ['.localhost', '127.0.0.1', '[::1]']
try:
	from .local_settings import *
except:
	pass

DATABASES = {
	'default': {
		'ENGINE': DATABASE_ENGINE, # Add 'postgresql_psycopg2', 'postgresql', 'mysql', 'sqlite3' or 'oracle'.
		'NAME': DATABASE_NAME,                      # Or path to database file if using sqlite3.
		'USER': DATABASE_USER,                      # Not used with sqlite3.
		'PASSWORD': DATABASE_PASSWORD,                  # Not used with sqlite3.
		'HOST': DATABASE_HOST,                      # Set to empty string for localhost. Not used with sqlite3.
		'PORT': DATABASE_PORT,                      # Set to empty string for default. Not used with sqlite3.
		'OPTIONS': DATABASE_OPTIONS,
	}
}
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
	},
	{
		'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
	},
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
	os.path.join(BASE_DIR, "static"),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
	"version": 1,  # the dictConfig format version
	"disable_existing_loggers": False,  # retain the default loggers
	"handlers": {
		"file": {
			"class": "logging.FileHandler",
			"filename": os.path.join(BASE_DIR,"general.log"),
		},
	},
	"loggers": {
		"": {
			"level": "DEBUG",
			"handlers": ["file"],
		},
	},
}
